version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd client
      - npm install
      - echo "📦 installing Front-end packages..."
      - echo "✅ Packages Front-end installed successfully."
  pre_build:
    commands:
      - npm run build
      - echo "⚙️ Testing..."
      - echo "✅ Tests passed successfully."
      - echo "🚧 Starting Front-end compiling packages..."
      - echo "✅ Build Front-end passed successfully."
  build:
    commands:
      - cd ../server
      - npm install
      - echo "📦 installing Back-end packages..."
      - echo "✅ Packages Back-end installed successfully."
  post_build:
    commands:
      - npm run build
      - echo "🚧 Starting Back-end compiling packages..."
      - echo "✅ Build Back-end passed successfully."
  artifacts:
    files:
      - '*/'
    base-directory: 
      - client/.next
      - server/dist
   
