version: 0.2

env:
  variables:
    PORT: "7500"
    PORT_FRONTEND: "3000"
    POSTGRES_HOST: "localhost"
    POSTGRES_USER: "postgres"
    POSTGRES_DB: "music-app"
    POSTGRESS_PASSWORD: "PDROf6{EcmxBT"
    POSTGRESS_PORT: "5432"
    PRIVATE_KEY: "secret_key_music_app"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd client
      - npm install
      - npm run build

  post_build:
    commands:
      - cd ../server
      - npm install
      - npm run build

