version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd client
      - npm install
      - echo "📦 installing Front-end packages..."
      - echo "✅ Packages Front-end installed successfully."
