version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd client
      - npm install
      - echo "📦 installing Front-end packages..."
      - echo "✅ Packages Front-end installed successfully."
  pre_build:
    commands:
      - npm run build
      - echo "⚙️ Testing..."
      - echo "✅ Tests passed successfully."
      - echo "🚧 Starting Front-end compiling packages..."
      - echo "✅ Build Front-end passed successfully."
